version: "3.7"

services:
  recipeapp-angular:
    build: ./recipeapp-angular
    networks:
      - front-end
      - back-end
    ports:
    - 4200:80
  recipe-app:
    build: ./recipe-app
    depends_on:
      - mysql
    ports:
    - 8081:8080
    networks:
      - front-end
      - back-end
  mysql:
    image: mysql:5.7
    networks:
      - back-end
    volumes:
      - recipe-app-data:/var/lib/mysql
      - ./db/setup.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: recipeapp
networks:
  front-end:
  back-end:
volumes:
  recipe-app-data:
